---
title: "footnotes"
format: html
---

## Format footnotes

In order to use footnote, we use \[\^x\], where x is the number you want superscripted in your text. At the bottom we insert \[\^x\]: (so we just add a colon)

Using the number 1 it would look like this:

This is my first footnote[^1]

[^1]: This is my first footnote content

If we need to insert a footnote, whose content contains multiple blocks/lines, we use \[\^longnote\] and \[\^longnote\]: . The subsequent line of the content is then indented to signal that it belongs to the footnote.

This is a long footnote[^2]

[^2]: This is a footnote with multiple blocks/lines

    Subsequent paragraphs are indented to show that they belong to the previous footnote.

There is another, perhaps simpler way to write footnote content. Instead of adding \[\^x\]: at the end of a block, we can use inline notes like this \^\[content\]

This is an inline note.[^3]

[^3]: Inline notes are very useful, since you don't have to pick an identifier/number and move down to type the note.

## References

This is the source I have used to for this task.[^4]

[^4]: https://www.datanovia.com/guide/tools/quarto/citations-and-footnotes.html
